package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class AuditoriaRespuestaAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertAuditoriaRespuestaAllPropertiesEquals(AuditoriaRespuesta expected, AuditoriaRespuesta actual) {
    assertAuditoriaRespuestaAutoGeneratedPropertiesEquals(expected, actual);
    assertAuditoriaRespuestaAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertAuditoriaRespuestaAllUpdatablePropertiesEquals(AuditoriaRespuesta expected, AuditoriaRespuesta actual) {
    assertAuditoriaRespuestaUpdatableFieldsEquals(expected, actual);
    assertAuditoriaRespuestaUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertAuditoriaRespuestaAutoGeneratedPropertiesEquals(AuditoriaRespuesta expected, AuditoriaRespuesta actual) {
    assertThat(actual)
      .as("Verify AuditoriaRespuesta auto generated properties")
      .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertAuditoriaRespuestaUpdatableFieldsEquals(AuditoriaRespuesta expected, AuditoriaRespuesta actual) {
    assertThat(actual)
      .as("Verify AuditoriaRespuesta relevant properties")
      .satisfies(a -> assertThat(a.getValorAnterior()).as("check valorAnterior").isEqualTo(expected.getValorAnterior()))
      .satisfies(a -> assertThat(a.getValorNuevo()).as("check valorNuevo").isEqualTo(expected.getValorNuevo()))
      .satisfies(a -> assertThat(a.getTimestampCambio()).as("check timestampCambio").isEqualTo(expected.getTimestampCambio()))
      .satisfies(a -> assertThat(a.getMotivoCambio()).as("check motivoCambio").isEqualTo(expected.getMotivoCambio()));
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertAuditoriaRespuestaUpdatableRelationshipsEquals(AuditoriaRespuesta expected, AuditoriaRespuesta actual) {
    assertThat(actual)
      .as("Verify AuditoriaRespuesta relationships")
      .satisfies(a -> assertThat(a.getRespuestaUsuario()).as("check respuestaUsuario").isEqualTo(expected.getRespuestaUsuario()))
      .satisfies(a -> assertThat(a.getDetalleRespuesta()).as("check detalleRespuesta").isEqualTo(expected.getDetalleRespuesta()));
  }
}
