package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CuestionarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuestionarioAllPropertiesEquals(Cuestionario expected, Cuestionario actual) {
        assertCuestionarioAutoGeneratedPropertiesEquals(expected, actual);
        assertCuestionarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuestionarioAllUpdatablePropertiesEquals(Cuestionario expected, Cuestionario actual) {
        assertCuestionarioUpdatableFieldsEquals(expected, actual);
        assertCuestionarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuestionarioAutoGeneratedPropertiesEquals(Cuestionario expected, Cuestionario actual) {
        assertThat(actual)
            .as("Verify Cuestionario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuestionarioUpdatableFieldsEquals(Cuestionario expected, Cuestionario actual) {
        assertThat(actual)
            .as("Verify Cuestionario relevant properties")
            .satisfies(a -> assertThat(a.getTitulo()).as("check titulo").isEqualTo(expected.getTitulo()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getInstrucciones()).as("check instrucciones").isEqualTo(expected.getInstrucciones()))
            .satisfies(a -> assertThat(a.getTotalPreguntas()).as("check totalPreguntas").isEqualTo(expected.getTotalPreguntas()))
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaActualizacion()).as("check fechaActualizacion").isEqualTo(expected.getFechaActualizacion())
            )
            .satisfies(a -> assertThat(a.getVersion()).as("check version").isEqualTo(expected.getVersion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCuestionarioUpdatableRelationshipsEquals(Cuestionario expected, Cuestionario actual) {
        // empty method
    }
}
