package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DetalleRespuestaAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertDetalleRespuestaAllPropertiesEquals(DetalleRespuesta expected, DetalleRespuesta actual) {
    assertDetalleRespuestaAutoGeneratedPropertiesEquals(expected, actual);
    assertDetalleRespuestaAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertDetalleRespuestaAllUpdatablePropertiesEquals(DetalleRespuesta expected, DetalleRespuesta actual) {
    assertDetalleRespuestaUpdatableFieldsEquals(expected, actual);
    assertDetalleRespuestaUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertDetalleRespuestaAutoGeneratedPropertiesEquals(DetalleRespuesta expected, DetalleRespuesta actual) {
    assertThat(actual)
      .as("Verify DetalleRespuesta auto generated properties")
      .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertDetalleRespuestaUpdatableFieldsEquals(DetalleRespuesta expected, DetalleRespuesta actual) {
    assertThat(actual)
      .as("Verify DetalleRespuesta relevant properties")
      .satisfies(a -> assertThat(a.getValorRespuesta()).as("check valorRespuesta").isEqualTo(expected.getValorRespuesta()))
      .satisfies(a -> assertThat(a.getTimestampRespuesta()).as("check timestampRespuesta").isEqualTo(expected.getTimestampRespuesta()))
      .satisfies(a ->
        assertThat(a.getTiempoPreguntaSegundos()).as("check tiempoPreguntaSegundos").isEqualTo(expected.getTiempoPreguntaSegundos())
      );
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertDetalleRespuestaUpdatableRelationshipsEquals(DetalleRespuesta expected, DetalleRespuesta actual) {
    assertThat(actual)
      .as("Verify DetalleRespuesta relationships")
      .satisfies(a -> assertThat(a.getEscalaRespuesta()).as("check escalaRespuesta").isEqualTo(expected.getEscalaRespuesta()))
      .satisfies(a -> assertThat(a.getPregunta()).as("check pregunta").isEqualTo(expected.getPregunta()))
      .satisfies(a -> assertThat(a.getRespuestaUsuario()).as("check respuestaUsuario").isEqualTo(expected.getRespuestaUsuario()));
  }
}
