package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class DonEspiritualAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonEspiritualAllPropertiesEquals(DonEspiritual expected, DonEspiritual actual) {
        assertDonEspiritualAutoGeneratedPropertiesEquals(expected, actual);
        assertDonEspiritualAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonEspiritualAllUpdatablePropertiesEquals(DonEspiritual expected, DonEspiritual actual) {
        assertDonEspiritualUpdatableFieldsEquals(expected, actual);
        assertDonEspiritualUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonEspiritualAutoGeneratedPropertiesEquals(DonEspiritual expected, DonEspiritual actual) {
        assertThat(actual)
            .as("Verify DonEspiritual auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonEspiritualUpdatableFieldsEquals(DonEspiritual expected, DonEspiritual actual) {
        assertThat(actual)
            .as("Verify DonEspiritual relevant properties")
            .satisfies(a -> assertThat(a.getNombre()).as("check nombre").isEqualTo(expected.getNombre()))
            .satisfies(a -> assertThat(a.getNombreCorto()).as("check nombreCorto").isEqualTo(expected.getNombreCorto()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getCaracteristicas()).as("check caracteristicas").isEqualTo(expected.getCaracteristicas()))
            .satisfies(a -> assertThat(a.getVersiculosBiblicos()).as("check versiculosBiblicos").isEqualTo(expected.getVersiculosBiblicos())
            )
            .satisfies(a -> assertThat(a.getActivo()).as("check activo").isEqualTo(expected.getActivo()))
            .satisfies(a -> assertThat(a.getOrdenPresentacion()).as("check ordenPresentacion").isEqualTo(expected.getOrdenPresentacion()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDonEspiritualUpdatableRelationshipsEquals(DonEspiritual expected, DonEspiritual actual) {
        // empty method
    }
}
