package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EscalaRespuestaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscalaRespuestaAllPropertiesEquals(EscalaRespuesta expected, EscalaRespuesta actual) {
        assertEscalaRespuestaAutoGeneratedPropertiesEquals(expected, actual);
        assertEscalaRespuestaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscalaRespuestaAllUpdatablePropertiesEquals(EscalaRespuesta expected, EscalaRespuesta actual) {
        assertEscalaRespuestaUpdatableFieldsEquals(expected, actual);
        assertEscalaRespuestaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscalaRespuestaAutoGeneratedPropertiesEquals(EscalaRespuesta expected, EscalaRespuesta actual) {
        assertThat(actual)
            .as("Verify EscalaRespuesta auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscalaRespuestaUpdatableFieldsEquals(EscalaRespuesta expected, EscalaRespuesta actual) {
        assertThat(actual)
            .as("Verify EscalaRespuesta relevant properties")
            .satisfies(a -> assertThat(a.getValor()).as("check valor").isEqualTo(expected.getValor()))
            .satisfies(a -> assertThat(a.getEtiqueta()).as("check etiqueta").isEqualTo(expected.getEtiqueta()))
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getOrden()).as("check orden").isEqualTo(expected.getOrden()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEscalaRespuestaUpdatableRelationshipsEquals(EscalaRespuesta expected, EscalaRespuesta actual) {
        // empty method
    }
}
