package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InterpretacionAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertInterpretacionAllPropertiesEquals(Interpretacion expected, Interpretacion actual) {
    assertInterpretacionAutoGeneratedPropertiesEquals(expected, actual);
    assertInterpretacionAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertInterpretacionAllUpdatablePropertiesEquals(Interpretacion expected, Interpretacion actual) {
    assertInterpretacionUpdatableFieldsEquals(expected, actual);
    assertInterpretacionUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertInterpretacionAutoGeneratedPropertiesEquals(Interpretacion expected, Interpretacion actual) {
    assertThat(actual)
      .as("Verify Interpretacion auto generated properties")
      .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertInterpretacionUpdatableFieldsEquals(Interpretacion expected, Interpretacion actual) {
    assertThat(actual)
      .as("Verify Interpretacion relevant properties")
      .satisfies(a -> assertThat(a.getPuntuacionMinima()).as("check puntuacionMinima").isEqualTo(expected.getPuntuacionMinima()))
      .satisfies(a -> assertThat(a.getPuntuacionMaxima()).as("check puntuacionMaxima").isEqualTo(expected.getPuntuacionMaxima()))
      .satisfies(a -> assertThat(a.getNivel()).as("check nivel").isEqualTo(expected.getNivel()))
      .satisfies(a -> assertThat(a.getDescripcionNivel()).as("check descripcionNivel").isEqualTo(expected.getDescripcionNivel()))
      .satisfies(a -> assertThat(a.getRecomendaciones()).as("check recomendaciones").isEqualTo(expected.getRecomendaciones()))
      .satisfies(a -> assertThat(a.getAreasServicio()).as("check areasServicio").isEqualTo(expected.getAreasServicio()));
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertInterpretacionUpdatableRelationshipsEquals(Interpretacion expected, Interpretacion actual) {
    assertThat(actual)
      .as("Verify Interpretacion relationships")
      .satisfies(a -> assertThat(a.getDonEspiritual()).as("check donEspiritual").isEqualTo(expected.getDonEspiritual()));
  }
}
