package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PreguntaDonAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaDonAllPropertiesEquals(PreguntaDon expected, PreguntaDon actual) {
    assertPreguntaDonAutoGeneratedPropertiesEquals(expected, actual);
    assertPreguntaDonAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaDonAllUpdatablePropertiesEquals(PreguntaDon expected, PreguntaDon actual) {
    assertPreguntaDonUpdatableFieldsEquals(expected, actual);
    assertPreguntaDonUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaDonAutoGeneratedPropertiesEquals(PreguntaDon expected, PreguntaDon actual) {
    assertThat(actual)
      .as("Verify PreguntaDon auto generated properties")
      .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaDonUpdatableFieldsEquals(PreguntaDon expected, PreguntaDon actual) {
    assertThat(actual)
      .as("Verify PreguntaDon relevant properties")
      .satisfies(a -> assertThat(a.getPeso()).as("check peso").isEqualTo(expected.getPeso()))
      .satisfies(a -> assertThat(a.getActiva()).as("check activa").isEqualTo(expected.getActiva()));
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaDonUpdatableRelationshipsEquals(PreguntaDon expected, PreguntaDon actual) {
    assertThat(actual)
      .as("Verify PreguntaDon relationships")
      .satisfies(a -> assertThat(a.getPregunta()).as("check pregunta").isEqualTo(expected.getPregunta()))
      .satisfies(a -> assertThat(a.getDonEspiritual()).as("check donEspiritual").isEqualTo(expected.getDonEspiritual()));
  }
}
