package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PreguntaAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaAllPropertiesEquals(Pregunta expected, Pregunta actual) {
    assertPreguntaAutoGeneratedPropertiesEquals(expected, actual);
    assertPreguntaAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaAllUpdatablePropertiesEquals(Pregunta expected, Pregunta actual) {
    assertPreguntaUpdatableFieldsEquals(expected, actual);
    assertPreguntaUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaAutoGeneratedPropertiesEquals(Pregunta expected, Pregunta actual) {
    assertThat(actual)
      .as("Verify Pregunta auto generated properties")
      .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaUpdatableFieldsEquals(Pregunta expected, Pregunta actual) {
    assertThat(actual)
      .as("Verify Pregunta relevant properties")
      .satisfies(a -> assertThat(a.getNumeroPregunta()).as("check numeroPregunta").isEqualTo(expected.getNumeroPregunta()))
      .satisfies(a -> assertThat(a.getTextoPregunta()).as("check textoPregunta").isEqualTo(expected.getTextoPregunta()))
      .satisfies(a -> assertThat(a.getObligatoria()).as("check obligatoria").isEqualTo(expected.getObligatoria()))
      .satisfies(a -> assertThat(a.getActiva()).as("check activa").isEqualTo(expected.getActiva()))
      .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()));
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertPreguntaUpdatableRelationshipsEquals(Pregunta expected, Pregunta actual) {
    assertThat(actual)
      .as("Verify Pregunta relationships")
      .satisfies(a -> assertThat(a.getCuestionario()).as("check cuestionario").isEqualTo(expected.getCuestionario()));
  }
}
