package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RespuestaUsuarioAsserts {

  /**
   * Asserts that the entity has all properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertRespuestaUsuarioAllPropertiesEquals(RespuestaUsuario expected, RespuestaUsuario actual) {
    assertRespuestaUsuarioAutoGeneratedPropertiesEquals(expected, actual);
    assertRespuestaUsuarioAllUpdatablePropertiesEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all updatable properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertRespuestaUsuarioAllUpdatablePropertiesEquals(RespuestaUsuario expected, RespuestaUsuario actual) {
    assertRespuestaUsuarioUpdatableFieldsEquals(expected, actual);
    assertRespuestaUsuarioUpdatableRelationshipsEquals(expected, actual);
  }

  /**
   * Asserts that the entity has all the auto generated properties (fields/relationships) set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertRespuestaUsuarioAutoGeneratedPropertiesEquals(RespuestaUsuario expected, RespuestaUsuario actual) {
    assertThat(actual)
      .as("Verify RespuestaUsuario auto generated properties")
      .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
  }

  /**
   * Asserts that the entity has all the updatable fields set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertRespuestaUsuarioUpdatableFieldsEquals(RespuestaUsuario expected, RespuestaUsuario actual) {
    assertThat(actual)
      .as("Verify RespuestaUsuario relevant properties")
      .satisfies(a -> assertThat(a.getFechaInicio()).as("check fechaInicio").isEqualTo(expected.getFechaInicio()))
      .satisfies(a -> assertThat(a.getFechaCompletado()).as("check fechaCompletado").isEqualTo(expected.getFechaCompletado()))
      .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
      .satisfies(a -> assertThat(a.getTiempoTotalSegundos()).as("check tiempoTotalSegundos").isEqualTo(expected.getTiempoTotalSegundos()))
      .satisfies(a -> assertThat(a.getIpAddress()).as("check ipAddress").isEqualTo(expected.getIpAddress()))
      .satisfies(a -> assertThat(a.getUserAgent()).as("check userAgent").isEqualTo(expected.getUserAgent()));
  }

  /**
   * Asserts that the entity has all the updatable relationships set.
   *
   * @param expected the expected entity
   * @param actual the actual entity
   */
  public static void assertRespuestaUsuarioUpdatableRelationshipsEquals(RespuestaUsuario expected, RespuestaUsuario actual) {
    assertThat(actual)
      .as("Verify RespuestaUsuario relationships")
      .satisfies(a -> assertThat(a.getCuestionario()).as("check cuestionario").isEqualTo(expected.getCuestionario()));
  }
}
