package ar.com.dones.app.domain;

import static ar.com.dones.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class ResultadoDonAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultadoDonAllPropertiesEquals(ResultadoDon expected, ResultadoDon actual) {
        assertResultadoDonAutoGeneratedPropertiesEquals(expected, actual);
        assertResultadoDonAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultadoDonAllUpdatablePropertiesEquals(ResultadoDon expected, ResultadoDon actual) {
        assertResultadoDonUpdatableFieldsEquals(expected, actual);
        assertResultadoDonUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultadoDonAutoGeneratedPropertiesEquals(ResultadoDon expected, ResultadoDon actual) {
        assertThat(actual)
            .as("Verify ResultadoDon auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultadoDonUpdatableFieldsEquals(ResultadoDon expected, ResultadoDon actual) {
        assertThat(actual)
            .as("Verify ResultadoDon relevant properties")
            .satisfies(a -> assertThat(a.getPuntuacionTotal()).as("check puntuacionTotal").isEqualTo(expected.getPuntuacionTotal()))
            .satisfies(a ->
                assertThat(a.getPorcentaje())
                    .as("check porcentaje")
                    .usingComparator(bigDecimalCompareTo)
                    .isEqualTo(expected.getPorcentaje())
            )
            .satisfies(a -> assertThat(a.getRankingPosicion()).as("check rankingPosicion").isEqualTo(expected.getRankingPosicion()))
            .satisfies(a -> assertThat(a.getEsDonPrincipal()).as("check esDonPrincipal").isEqualTo(expected.getEsDonPrincipal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertResultadoDonUpdatableRelationshipsEquals(ResultadoDon expected, ResultadoDon actual) {
        assertThat(actual)
            .as("Verify ResultadoDon relationships")
            .satisfies(a -> assertThat(a.getInterpretacion()).as("check interpretacion").isEqualTo(expected.getInterpretacion()))
            .satisfies(a -> assertThat(a.getRespuestaUsuario()).as("check respuestaUsuario").isEqualTo(expected.getRespuestaUsuario()))
            .satisfies(a -> assertThat(a.getDonEspiritual()).as("check donEspiritual").isEqualTo(expected.getDonEspiritual()));
    }
}
