package ar.com.dones.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SesionUsuarioAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioAllPropertiesEquals(SesionUsuario expected, SesionUsuario actual) {
        assertSesionUsuarioAutoGeneratedPropertiesEquals(expected, actual);
        assertSesionUsuarioAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioAllUpdatablePropertiesEquals(SesionUsuario expected, SesionUsuario actual) {
        assertSesionUsuarioUpdatableFieldsEquals(expected, actual);
        assertSesionUsuarioUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioAutoGeneratedPropertiesEquals(SesionUsuario expected, SesionUsuario actual) {
        assertThat(actual)
            .as("Verify SesionUsuario auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioUpdatableFieldsEquals(SesionUsuario expected, SesionUsuario actual) {
        assertThat(actual)
            .as("Verify SesionUsuario relevant properties")
            .satisfies(a ->
                assertThat(a.getRespuestasTemporales()).as("check respuestasTemporales").isEqualTo(expected.getRespuestasTemporales())
            )
            .satisfies(a -> assertThat(a.getFechaCreacion()).as("check fechaCreacion").isEqualTo(expected.getFechaCreacion()))
            .satisfies(a -> assertThat(a.getFechaExpiracion()).as("check fechaExpiracion").isEqualTo(expected.getFechaExpiracion()))
            .satisfies(a -> assertThat(a.getCompletada()).as("check completada").isEqualTo(expected.getCompletada()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSesionUsuarioUpdatableRelationshipsEquals(SesionUsuario expected, SesionUsuario actual) {
        assertThat(actual)
            .as("Verify SesionUsuario relationships")
            .satisfies(a -> assertThat(a.getUsuario()).as("check usuario").isEqualTo(expected.getUsuario()))
            .satisfies(a -> assertThat(a.getRespuestaUsuario()).as("check respuestaUsuario").isEqualTo(expected.getRespuestaUsuario()));
    }
}
